model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 64

exp_params:
  dataset: cosmo
  img_size: 64
  batch_size: 1024 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0001
  num_workers : 16
  max_epochs: 100

trainer_params:
  gpus: 1
  max_epochs: 100
#  accelerator: "ddp"



logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
