model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 64

exp_params:
  dataset: cosmo
  img_size: 64
  batch_size: 64 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  num_workers : 8
  max_epochs: 30

trainer_params:
  gpus: 1
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
