model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 64

exp_params:
  dataset: cosmo
  img_size: 64
  batch_size: 32 # Better to have a square number
  LR: 0.0005
  weight_decay: 0.0001
  num_workers : 8
  max_epochs: 10
  load_every: 1

trainer_params:
  gpus: 2
  max_epochs: 10
  accelerator: "ddp"



logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
